### ISSUE TITLE
Installation Error!

### ISSUE THREAD

**Issue by Muhammad-Usman-Amin** [c-Cyril-l/Asphalt9Materials#1]
While Installing the setup file It gives different errors! Plz see it in the screenshots!
I've MS Net Framework 7 plus and MS SQL Server 2019 Installed already!
![20200113_142844](https://user-images.githubusercontent.com/32971066/72245740-0ab2f400-3613-11ea-9863-6be743e21a33.jpg)
![20200113_142833](https://user-images.githubusercontent.com/32971066/72245741-0ab2f400-3613-11ea-97be-fd10323bcb5e.jpg)

**Comment by c-Cyril-l** [comment]
Thanks for the report, I modified the installation as well as updated the source, you can check it again and see if it works for you.
Note : The SQL Server Edition must be "Express" edition ("SQL Server Express 2017 or higher").
Here is the Installation video as well
https://www.youtube.com/watch?v=44jjPia3a_U&list=PL-KKJ2dgWqTHQ_HcN43P9mLyWgF4IB94o&index=2&t=4s
